### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by hanneskod** [byrokrat/id#17]
2018 will see ver 2.0. Here is the todo list

* [x] remov deprecated classes and metods
* [x] require php 7 and use scalar type declarations and return type declarations
* [x] DateTimeInterface instead of DateTime
* [x] phpunit ~~6~~ 7 
* [x] constant array expressions instead of private static..
* [x] BirthCountyInterface, LegalFormInterface...

**Comment by jongotlin** [comment]
Do you want help with this? If you create a 2.0 branch I can probably help with some of the above tasks.

**Comment by hanneskod** [comment]
Awesome. The branch is there now, and all help is much appreciated!
